### ISSUE TITLE
ImageMosaic behaviour on Tiled requests

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#101]
Making single Tile GetMaps against the Mosaic I get the following output:
![single_tile](https://user-images.githubusercontent.com/5264230/28716756-2e37abd4-739f-11e7-9a1e-8d71a6b00faa.png)

Result is different when making tiled requests
![tiled](https://user-images.githubusercontent.com/5264230/28716757-2e5234c2-739f-11e7-9295-98b9637e4be6.png)

**Comment by aaime** [comment]
This is actually due to a GWC bug: https://osgeo-org.atlassian.net/browse/GEOS-8279
