### ISSUE TITLE
products OGC URLs encoding in GeoServer

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#102]
For instance we have GetCapabilities and GetMap links as follows in table "**product_ogclink**":
GetCapabilities link:
`${BASE_URL}/test/SENTINEL1_MOSAIC/ows?service=wms&request=GetCapabilities&version=1.3.0&CQL_FILTER=eoParentIdentifier='S1B_EW_GRDM_1SDV_20161202T165803_20161202T165906_003220_0057B6_CEB5'
`
and GetMap link:
`${BASE_URL}/test/SENTINEL1_MOSAIC/ows?service=wms&request=GetMap&version=1.3.0&LAYERS=SENTINEL1_MOSAIC&BBOX=8.64903277523,46.082521531,15.3109925948,50.5513093277&WIDTH=768&HEIGHT=768&FORMAT=image/jpeg&CQL_FILTER=eoIdentifier='S1B_EW_GRDM_1SDV_20161202T165803_20161202T165906_003220_0057B6_CEB5'`

And ask for that product via OpenSearch:
http://cloudsdi.geo-solutions.it/geoserver/oseo/search?parentId=SENTINEL1&identifier=S1B_EW_GRDM_1SDV_20161202T165803_20161202T165906_003220_0057B6_CEB5

WMS link returned are not encoded correctly:
```
    <owc:offering code="http://www.opengis.net/spec/owc/1.0/req/atom/wms">
      <owc:operation method="GET" code="GetCapabilities" href="http://cloudsdi.geo-solutions.it:80/geoserver/test/SENTINEL1_MOSAIC/ows?service=wms&amp;request=GetCapabilities&amp;version=1.3.0&amp;CQL_FILTER=eoParentIdentifier='S1B_EW_GRDM_1SDV_20161202T165803_20161202T165906_003220_0057B6_CEB5'" type="application/xml"/>
      <owc:operation method="GET" code="GetMap" href="http://cloudsdi.geo-solutions.it:80/geoserver/test/SENTINEL1_MOSAIC/ows?service=wms&amp;request=GetMap&amp;version=1.3.0&amp;LAYERS=SENTINEL1_MOSAIC&amp;BBOX=8.64903277523,46.082521531,15.3109925948,50.5513093277&amp;WIDTH=768&amp;HEIGHT=768&amp;FORMAT=image/jpeg&amp;CQL_FILTER=eoIdentifier='S1B_EW_GRDM_1SDV_20161202T165803_20161202T165906_003220_0057B6_CEB5'" type="image/jpeg"/>
    </owc:offering>

```

**Comment by aaime** [comment]
I believe we discussed this and agreed the encoding is actually correct, that is a bit of XML and & must be replaced by its entity "&amp;", e.g:
https://stackoverflow.com/questions/7823813/how-can-i-use-character-in-xml-code

**Comment by randomorder** [comment]
@aaime 
Looks correct to me. Closing this one
