### ISSUE TITLE
Airflow DAGs to produce product.zip for Landsat8

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#104]
Implement Airflow Operators and DAGs to produce a product.zip archive to be ingested by GeoServer.
Archive must contain the following:

- [x] product.json
Populated with relevant OpenSearch searchable attributes and product "footprint'. It is ok for the moment to only fetch the available attributes from the MTL file.

- [x] granules.json
Populated with granules bouningBoxes and "location" properties ( base directory for the "location" property must be configurable )

- [x] thumbnail.jpeg
Compressed, low resolution, square shaped 

- [x] description.html
Rendered from a Jinja template (see Sentinel1 example)

- [x] metadata.xml
In first implementation just a placeholder file taken from example product.zip. To be improved using Jinja template and populating relevant tags

**Comment by maabdelghaffar** [comment]
The description.html is also using startTime and stopTime which are not available in .MTL file and could be fetched from USGS as mentioned in issue #100

**Comment by maabdelghaffar** [comment]
please note that description.html and metadata.xml are currently not implemented and just placeholders
