### ISSUE TITLE
Airflow DAG to ingest Sentinel 2 products

### ISSUE THREAD

**Issue by maabdelghaffar** [geosolutions-it/evo-odas#107]
### Description:
This dag contains steps that were exposed before during Sentinel-1 dag development.
The requirements are: 

- [x] Search & Download Sentinel-2 granules: The Search operator is already implemented in Sentinel-1, we just need to configure the dag to point to Sentinel-2 by changing the platform_name parameter and also changing the file_name parameter to match with Sentinel-2 naming convention. While the Download operator is also implemented, however, we just need to add a new directory for Sentinel-2 downloads.

- [x] #119 Archive package: After downloading the zip file of the product, keep a copy from the zip file as the user may need to download products later on. (? are we keeping a copy from the whole .zip of the product or just a copy from the individual bands ?) 

- [x] Read and Ingest granules metadata: In which we gonna utilize from Damiano's code [here](https://github.com/geosolutions-it/evo-odas/tree/master/metadata-ingestion) to read the products metadata. here we need to make sure to map as many as possible from the attributes and update [this sheet](https://docs.google.com/spreadsheets/d/1kWywFZoAywvLoWZA4A_h5Cp9mf5x_s8Qvsf2jr6Mz08/edit?ts=5976fbd3)

- [x] Create product.zip: After reading all the required metadata from the previous step, here we will create the following files and compress then in product.zip file. 
- 1- granules.json [required]
- 2- product.json [required]
- 3- description.html [required]
- 4- metadata.xml [just a copy from the product.zip example file]
- 5- owslinks.json [just a copy from the product.zip example file]
- 6- thumbnail.jpeg [required]
Note that some of these files creation steps were already implemented but not in form of Airflow operators, so we can use the same steps but we will need to turn them to Airflow operators inside that dag. please refer to the product.zip example.

Notes: 
- Sentinel-2 doesn't require any processing to be done (e.g Warping, Translating or Addo).
- The AOI is currently same as Sentinel-1 "Germany"

**Comment by maabdelghaffar** [comment]
S2reader is not working properly and issue has been reported.

**Comment by maabdelghaffar** [comment]
please note that metadata.xml, description.html and owslinks.json are just placeholders in this version

**Comment by randomorder** [comment]
S2Reader issue should be fixed now #108
