### ISSUE TITLE
Implement original package upload for Sentinel 2 products

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#119]
Implement original package upload using existing RSYNCOperator in order to have original package publicly available for download ( for instance here: http://cloudsdi.geo-solutions.it/data/sentinel/ ).
The final publicly reachable URL should be used in product.zip ( see product originalPackageLocation )

**Comment by randomorder** [comment]
Take a look at the S1 upload as an example
https://github.com/randomorder/evo-odas/blob/metadata/airflow/dags/sentinel1/S1_Process_Publish_EW_GRDM_1SDV.py#L87

Note that you should test it locally on your machine, you Don't need SSH access to CloudSDI

**Comment by maabdelghaffar** [comment]
Done with creating .tfw and .prj files in addition to the granules to be uploaded via RSYNC operator

**Comment by randomorder** [comment]
Looks like original package location in "null" in final product.json . Needs investigation

After fixing the above, for the long term we could investigate and think of using AWS's S3 for the original package. As @maabdelghaffar pointed out looks like are available for download from S3
http://sentinel-pds.s3-website.eu-central-1.amazonaws.com/
This way we'd get rid of the original package upload step for S2

**Comment by randomorder** [comment]
'originalPackageLocation' not populated for S2 products. Investigation required
