### ISSUE TITLE
Implement Sentinel 2 Publishing Task

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#122]
Implement simple task to publish ( HTTP POST ) Sentinel 2 product.zips to GeoServer via REST API

**Comment by simboss** [comment]
@randomorder do we already have a task for the original package upload? Is it already implemented?

**Comment by randomorder** [comment]
Yes, original package upload is already implemented. We still have to implement the publishing of  product.zip into GeoServer via REST

**Comment by simboss** [comment]
thx.
