### ISSUE TITLE
Add OWS links for Sentinel 2 in product.zip

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#124]
Currently OWS links in product.zip are not populated by the Airflow DAG.

Add proper OWS links in product.zip to include:
WFS links
- [x] WFS GetCapabilities
- [x] WFS GetFeature

WMS links
- [x] WMS GetCapabilities
- [x] WMS GetMap

WCS links
- [x] WCS GetCapabilities
- [x] WCS GetCoverage

**Comment by randomorder** [comment]
Take a look at the S1 draft implementation to understand how to populate the owslinks.json file:
https://github.com/randomorder/evo-odas/blob/metadata/airflow/dags/sentinel1/utils/ssat1_metadata.py#L188

Currently only contains WMS links but links to other services will be included and must be included for S2 as well

For instance this is how the GetCoverage URL looks like for one of the S1 products:
${BASE_URL}/test/wcs?service=WCS&version=2.0.1&coverageId=test__SENTINEL1_MOSAIC&request=GetCoverage&format=geotiff&subset=http://www.opengis.net/def/axis/OGC/0/Long(29.775306144184533,39.03923800614894)&subset=http://www.opengis.net/def/axis/OGC/0/Lat(63.554792496416276,65.6704742324595)&scaleaxes=i(0.1),j(0.1)&CQL_FILTER=eoIdentifier='S1B_EW_GRDM_1SDH_20170605T041508_20170605T041530_005910_00A5D8_6AE4'

coverageId must be configurable
Long and Lat extracted from the product
and a CQL FILTER with product  id must be included

**Comment by randomorder** [comment]
Here is my initial feddback after briefly testing:

`{
    "links": [
        {
            "href": "${BASE_URL}/S2XYZ_Workspace/S2XYZ_Layer/ows?service=wms&request=GetCapabilities&version=1.3.0&CQL_FILTER=eoParentIdentifier='S2A_MSIL1C_20170910T104021_N0205_R008_T32UMG_20170910T104212'", 
            "code": "GetCapabilities", 
            "type": "application/xml", 
            "method": "GET", 
            "offering": "http://www.opengis.net/spec/owc-atom/1.0/req/wms"
        }, 
        {
            "href": "${BASE_URL}/S2XYZ_Workspace/S2XYZ_Layer/ows?service=wfs&request=GetCapabilities&version=1.3.0&CQL_FILTER=eoParentIdentifier='S2A_MSIL1C_20170910T104021_N0205_R008_T32UMG_20170910T104212'", 
            "code": "GetCapabilities", 
            "type": "application/xml", 
            "method": "GET", 
            "offering": "http://www.opengis.net/spec/owc-atom/1.0/req/wfs"
        }, 
        {
            "href": "${BASE_URL}/S2XYZ_Workspace/S2XYZ_Layer/ows?service=wcs&request=GetCapabilities&version=1.3.0&CQL_FILTER=eoParentIdentifier='S2A_MSIL1C_20170910T104021_N0205_R008_T32UMG_20170910T104212'", 
            "code": "GetCapabilities", 
            "type": "application/xml", 
            "method": "GET", 
            "offering": "http://www.opengis.net/spec/owc-atom/1.0/req/wcs"
        }, 
        {
            "href": "${BASE_URL}/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&typeNames=S2XYZ_Workspace:S2XYZ_Layer&CQL_FILTER=eoIdentifier='S2A_MSIL1C_20170910T104021_N0205_R008_T32UMG_20170910T104212'&outputFormat=application/json", 
            "code": "GetFeature", 
            "type": "application/json", 
            "method": "GET", 
            "offering": "http://www.opengis.net/spec/owc-atom/1.0/req/wfs"
        }, 
        {
            "href": "${BASE_URL}/test/wcs?service=WCS&version=2.0.1&coverageId=S2_XYZ_CID&request=GetCoverage&format=jpeg2000&subset=http://www.opengis.net/def/axis/OGC/0/**Long(7.43801827302,9.15627174927)&subset=http://www.opengis.net/def/axis/OGC/0/Lat(54.9490659901,55.9456353211)**&scaleaxes=i(0.1),j(0.1)**&CQL_FILTER=eoIdentifier='S2A_MSIL1C_20170910T104021_N0205_R008_T32UMG_20170910T104212'", 
            "code": "GetCoverage", 
            "type": "application/json", 
            "method": "GET", 
            "offering": "http://www.opengis.net/spec/owc-atom/1.0/req/wcs"
        }, 
        {
            "code": "GetMap", 
            "href": "${BASE_URL}/S2XYZ_Workspace/S2XYZ_Layer/ows?service=wms&request=GetMap&version=1.3.0&LAYERS=S2XYZ_Layer&BBOX=7.438018273024498,54.94906599009572,9.156271749270051,55.94563532105239&WIDTH=512&HEIGHT=512&FORMAT=image/jpeg&CQL_FILTER=eoIdentifier='S2A_MSIL1C_20170910T104021_N0205_R008_T32UMG_20170910T104212'", 
            "type": "image/jpeg", 
            "method": "GET", 
            "offering": "http://www.opengis.net/spec/owc-atom/1.0/req/wms"
        }
    ]
}
`
- WCS GetCoverage request has "test" workspace hardcoded in it
- WCS GetCoverage has some asterisks in it. Sample request in the comment above had asterisks to format it in the Github comment but should not end up in the WCS request

> **

> 
- type for GetCoverage is "application/json":

>             "type": "application/json",

**Comment by maabdelghaffar** [comment]
right and fixed already
