### ISSUE TITLE
Add support for parsing georeferentiation for S2 granules

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#152]
Sentinel 2 jpeg 2000 granules carry the georeferentiation information as an embedded GML into the granules themselves. We currently cannot publish the granules as parsing this is not supported by GeoServer.

As a temporary workaround create an auxiliary world file for each granule containing the georeferentiation information

**Comment by maabdelghaffar** [comment]
the world file saved as .wld instead of .tfw

**Comment by randomorder** [comment]
This issue is on Geoserver side, not about adding World Files

**Comment by simboss** [comment]
The Kakadu direct plugin does not support georeferencing using GMLJP2 but only GeoJP2 and World File.

We should review what GDAL does with respect to parsing the georeferencing, I would not create a full blown GML parser for just this.

**Comment by simboss** [comment]
@aaime  this should be logged on the Adwaiseo project (talking about timesheet).
