### ISSUE TITLE
Wrong "location" property in S2's granules.json

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#154]
The "location" property of the granules in the granules.json file contained in the product.zip is not set correctly.
For instance:
```
...
"location":"/vsizip//var/data/download/Sentinel-2/S2A_MSIL1C_20170829T100031_N0205_R122_T33UWS_20170829T100026.zip/S2A_MSIL1C_20170829T100031_N0205_R122_T33UWS_20170829T100026.SAFE/GRANULE/L1C_T33UWS_A011416_20170829T100026/IMG_DATA/S2A_OPER_MSI_L1C_TL_SGS__20170829T152942_A011416_T33UWS_B12.jp2"
...
```

"location" should point to the path where the granules were uploaded on the remote server (basically hte path where the  "sentinel2_upload_granules" task have uploaded the granules). In current implementation it pointing to a path inside the zip file (maybe inside the original package?)

**Comment by maabdelghaffar** [comment]
yeah, it was pointing to the path inside the original package, will be updated
