### ISSUE TITLE
Fix files that are tracked by git but are also added to .gitignore

### ISSUE THREAD

**Issue by ricardogsilva** [geosolutions-it/evo-odas#158]
The following files are in `.gitignore` but are at the same time tracked by git:

```
evo-odas/airflow/docker/airflow.cfg
evo-odas/airflow/plugins/gdal_plugin.py
```

Might be an issue with wrong `.gitignore` directives though.

**Comment by randomorder** [comment]
Makes sense to have them airflow.cfg in the repo to allow users to build a custom the Docker image.
gdal_plugin.py should definetly be tracked

https://github.com/geosolutions-it/evo-odas/pull/195
