### ISSUE TITLE
Unpredictable JPEG2000 reader used in mosaic

### ISSUE THREAD

**Issue by aaime** [geosolutions-it/evo-odas#170]
Setting up a JPEG2000 based reader might end up using, as the mosaic preferred SPI, either the Kakadu reader or the Sun reader. When the Sun reader is used nothing gets displayed.

Current work-around is to change the mosaic preffered SPI from:
com.sun.media.imageioimpl.plugins.jpeg2000.J2KImageReader
to:
it.geosolutions.imageio.plugins.jp2k.JP2KKakaduImageReaderSpi

KakaduUtils tries to register itself, but if imageio-core is later in the classpath, it will register itself first.

**Comment by aaime** [comment]
Idea: modify GeoServerInitStartupListener to scan all the readers and re-order them so that the GeoSolutions ones are first? Otherwise we'd have to add this kind of logic in both CollectionsController (opensearch) and imagemosaic. Downside, a pure geotools based application might fall in this trap.

**Comment by aaime** [comment]
Marking this one as a blocker since the manual fix to the preferred SPI cannot be done during the workshop demo

**Comment by simboss** [comment]
I see another path, I'll let you @aaime (talk to @dromagnoli maybe) decide the best one.

Long story short JJ2000 is unusable therefore I would just remove it an use only kakadu.

**Comment by aaime** [comment]
We also discussed that option, in terms of re-packaging imageio not to have those classes. Or did you think of doing it programmatically, in GeoserverInitStartupListener?

**Comment by simboss** [comment]
Good point, I did not think about the fact that JJ2000 is within ImageIO.

I would suggest short term plan to remove it using your approach, longer term plan to remove it from ImageIO itself.
