### ISSUE TITLE
Add properties for multiband / heterogeneous mosaic support in S2 product.zip 

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/evo-odas#171]
In order to handle multiband / heterogeneous Mosaics in GeoServer new properties need to be added into product.json and granules.json files in the product.zip

- [x] product.json must have a "crs" property containing the CRS of the granules. For instance:

...
      "eop:acquisitionStation":null,
      "timeStart":"2017-09-04T10:20:21.026Z",
      "eop:processingCenter":null,
      "eop:illuminationAzimuthAngle":null,
      "eop:orbitDirection":"DESCENDING",
      "eop:sensorMode":null,
      "quicklookURL":null,
      "eop:availabilityTime":null,
      **"crs":"EPSG:32632"**
   }
...

- [x] granules.json must have a "band" property containing a the band number for each granule. For instance:
...
         "type":"Feature",
         "properties":{                     "location":"/efs/geoserver_data/coverages/sentinel/sentinel2/sentinel2/L1C_T32UNC_A011502_20170904T102511/IMG_DATA/T32UNC_20170904T102021_B04.jp2"
         **"band":"4"**
         },
...
Number associated with each band must start from 1 and be configurable in some way. For example using a dictionary to hold the relationship between bands and numbers:
```
bands_dict = {
	'1':1,
	'2':2,
	'3':3,
	'4':4,
	'5':5,
	'6':6,
	'7':7,
	'8':8,
	'8A':9,
	'9':10,
	'10':11,
	'11':12,
	'12':13,
	'TCI':14,
}
```

**Comment by maabdelghaffar** [comment]
in the example above, the  "band":"1" should be "band":"4" instead ?

**Comment by randomorder** [comment]
correct, comment updated
