### ISSUE TITLE
Problem between Sort By and CQL_FILTER

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/evo-odas#175]
This is a problem with the cloudsdi deploy and the Zaatari ImageMosaic which has the structure below:

![2017-08-09_1649](https://user-images.githubusercontent.com/693880/30117715-53257ea2-9321-11e7-8ce7-95ac3e453bb0.png)

Italian explanation follows:

​Quindi filtrando con "sun_elevation > 50" seleziono solo il 2016 (ho usato TIME=2000/3000 per prendere tutti granuli):

http://cloudsdi.geo-solutions.it/geoserver/zaatari/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&STYLES&TIME=2000%2F3000&LAYERS=zaatari%3Azaatari_worldview_timeseries&SRS=EPSG%3A4326&WIDTH=768&HEIGHT=363&BBOX=36.26089096069336%2C32.26315498352051%2C36.39272689819336%2C32.32546806335449&CQL_FILTER=sun_elevation%3E50

Se alla stessa richiesta aggiungo "SORTBY= time A" ottengo anche le immagini del 2013:

http://cloudsdi.geo-solutions.it/geoserver/zaatari/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&STYLES&TIME=2000%2F3000&LAYERS=zaatari%3Azaatari_worldview_timeseries&SRS=EPSG%3A4326&WIDTH=768&HEIGHT=363&BBOX=36.26089096069336%2C32.26315498352051%2C36.39272689819336%2C32.32546806335449&CQL_FILTER=sun_elevation%3E50&SORTBY=time%20A

Con "SORTBY= time D" si vede l'immagine del 2017 (che copre il resto):

http://cloudsdi.geo-solutions.it/geoserver/zaatari/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&STYLES&TIME=2000%2F3000&LAYERS=zaatari%3Azaatari_worldview_timeseries&SRS=EPSG%3A4326&WIDTH=768&HEIGHT=363&BBOX=36.26089096069336%2C32.26315498352051%2C36.39272689819336%2C32.32546806335449&CQL_FILTER=sun_elevation%3E50&SORTBY=time%20D

Analogamente filtrando con "sun_elevation < 50" si vedono i granuli giusti (2013 e 2017)

http://cloudsdi.geo-solutions.it/geoserver/zaatari/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&STYLES&TIME=2000%2F3000&LAYERS=zaatari%3Azaatari_worldview_timeseries&SRS=EPSG%3A4326&WIDTH=768&HEIGHT=363&BBOX=36.26089096069336%2C32.26315498352051%2C36.39272689819336%2C32.32546806335449&CQL_FILTER=sun_elevation%3C50

Mentre con il SORTBY riappare anche il 2016

http://cloudsdi.geo-solutions.it/geoserver/zaatari/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&STYLES&TIME=2000%2F3000&LAYERS=zaatari%3Azaatari_worldview_timeseries&SRS=EPSG%3A4326&WIDTH=768&HEIGHT=363&BBOX=36.26089096069336%2C32.26315498352051%2C36.39272689819336%2C32.32546806335449&CQL_FILTER=sun_elevation%3C50&SORTBY=time%20A

http://cloudsdi.geo-solutions.it/geoserver/zaatari/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fjpeg&TRANSPARENT=true&STYLES&TIME=2000%2F3000&LAYERS=zaatari%3Azaatari_worldview_timeseries&SRS=EPSG%3A4326&WIDTH=768&HEIGHT=363&BBOX=36.26089096069336%2C32.26315498352051%2C36.39272689819336%2C32.32546806335449&CQL_FILTER=sun_elevation%3C50&SORTBY=time%20D

**Comment by aaime** [comment]
It is happening because the mosaic has "caching=true" and the in memory caching store cannot handle filtering and sorting properly. Setting it to caching is something that, afaik, we never do though? 
It breaks the ability to change the underlying database and see the new granules.

I'll see how hard it is to fix the caching store.
