### ISSUE TITLE
TimestampFileNameExtractorSPI to extract correcly Julian days from filenames

### ISSUE THREAD

**Issue by fernandinand** [geosolutions-it/evo-odas#4]
Landsat8 images follow a naming convention like this:
`LC81390452014295LGN00`

From here we can extract the date in julian days (YYYYDDD) in this case `2014295` when building a mosaic in geoserver with time dimension.
The following setup of timeregex.properties is not able to retrieve correctly the date from the filename:
`format=YYYYDDD
regex=.{9}([0-9].{6})`

[sample image](http://landsat-pds.s3.amazonaws.com/L8/139/045/LC81390452014295LGN00/LC81390452014295LGN00_B2.TIF)
[mosaic_init.zip](https://github.com/geosolutions-it/evo-odas/files/513424/mosaic_init.zip)

**Comment by dromagnoli** [comment]
The following pattern should work:
regex=(?<=[a-zA-Z0-9]{9}){6}[0-9]+(?=[a-zA-Z0-9]{5}),format=yyyyDDD
