### ISSUE TITLE
[Geoserver] WCS getCoverage cql_filter returns a wrong BBOX

### ISSUE THREAD

**Issue by Damianofds** [geosolutions-it/evo-odas#71]
When filtering via cql_filter a **WCS getCoverage** request against an imagemosaic to get one single granule, the output granule still has the mosaic original BBOX.

**Is this the right behavior we want?**

**Comment by aaime** [comment]
I've checked the code, it's a mix between the request made and the image mosaic behavior. When no bbox is explicitly specified, the request uses a grid geometry matching the reader declared one (which is, the full mosaic) and then the mosaic respecting it to the letter even if only a single granule is extracted.

Possible approaches:
* Have the image mosaic only return what it actually has, without padding (it's a valid response as far as I know)
* Have WCS recognize the structured grid reader, and figure out the filtered extent using GranuleSource (this could also be used in DescribeCoverage, coupled with the parameter extension it would make for a true "single granule" WCS service)

@simboss comments?
