### ISSUE TITLE
implement a configuration operator

### ISSUE THREAD

**Issue by Damianofds** [geosolutions-it/evo-odas#79]
The first step of each workflow must check if there are the right environment properties.
Some examples:
* Check for the disk quota
* Check if the related collection of the product we are ingesting exist
* Check if the product already exist

This operator should be agnostic about the product we are ingesting and it should be reusable for any workflow (DAG) we want to create.

**Comment by simboss** [comment]
@randomorder is this still on? Do we leave it open?

**Comment by randomorder** [comment]
Some of this seems superfluous to me and I don't think this should end up in a new Operator anyway.

Check for the disk quota - We don't necessarely know how much disk space is needed, also the granules may end up in a remote server. This should probably be done by an external monitoring tool (NewRelic for instance)
Check if the related collection of the product we are ingesting exist - This could be a call to GeoServer's REST API
Check if the product already exist - This could be a call to GeoServer's REST API. There is a duplicate issue for this #133

Closing this one and creating a separate issue for "Check if the related collection of the product we are ingesting exist"

**Comment by randomorder** [comment]
Check if the product already exist: #174
