### ISSUE TITLE
wrap gdalinfo

### ISSUE THREAD

**Issue by Damianofds** [geosolutions-it/evo-odas#84]
Wrap the **gdalinfo** utility in an airflow operator, the idea is to keep it as simple as possible in order to define a basic building blocks. 
* don't expose all of the gdalinfo options but only those required by the evo-odas processing
* it should work on a single image per time
* A nice to have would be a config parameter to subset the output
   e.g. "ALL" returns all the gdalinfo output
          "CRS" returns only the info related to crs
          "BBOX" returns only the info related to the bbox
          ecc...

**Comment by simboss** [comment]
@randomorder is this still valid?

**Comment by randomorder** [comment]
Yes, not implemented yet

**Comment by randomorder** [comment]
#223 implements GDALInfo Operator without the subset parameter
