### ISSUE TITLE
[airflow operator] Create thumbnails operator

### ISSUE THREAD

**Issue by maabdelghaffar** [geosolutions-it/evo-odas#95]
**Requirements:**

To create thumbnails (small size image) from landsat-8 scenes (bands to be determined)

**Approach:**

- To use gdal_translate with "-outsize" option to set the thumbnail desired dimensions
- This will require to use gdal_info before the mentioned above step so that we can get the original dimensions of the scene
- The above step is necessary to keep the aspect ratio of the newly created thumbnail matching with the original scene dimensions

**Comment by randomorder** [comment]
See #147
